from django.test import TestCase
from generator_core.utils.nlp.nlp_openai_util import nlp_openai, NLP_OpenAI_Exception

class TestNLP_OpenAI(TestCase):
    pass